version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: puttputtpal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - puttputtpal_net
      - redis-network
  api:
    container_name: puttputtpal-server
    image: index.docker.io/mcanziani1/puttputtpal-server:latest
    env_file:
      - .env.server.production
    environment:
      - REDIS_HOST=redis
    volumes:
      - /var/log/puttputtpal/all.log:/app/logs/server/all.log
      - /var/log/puttputtpal/error.log:/app/logs/server/error.log
    networks:
      - puttputtpal_net
    ports:
      - "7500:7500"
      
# create network externally with docker network create puttputtpal_net
networks:
  puttputtpal_net:
    external: true
  redis-network:
    driver: bridge

volumes:
  redis-data: