version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/puttputtpal.com.crt:/etc/ssl/certs/puttputtpal.com.crt
      - ./certs/puttputtpal.com.key:/etc/ssl/private/puttputtpal.com.key
      - ./cloudflare-ips.conf:/etc/nginx/cloudflare-ips.conf
    networks:
      - puttputtpal_net

networks:
  puttputtpal_net:
    name: puttputtpal_net
    driver: bridge