version: '3.8'
services:
  api:
    container_name: puttputtpal-server
    image: index.docker.io/mcanziani1/puttputtpal-server:latest
    env_file:
      - .env.server.production
    volumes:
      - /var/log/puttputtpal/all.log:/app/logs/server/all.log
      - /var/log/puttputtpal/error.log:/app/logs/server/error.log
    networks:
      - puttputtpal_net
    ports:
      - "7500:7500"

  redis:
    image: redis:latest
    container_name: puttputtpal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
      - puttputtpal_net
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/puttputtpal.com.crt:/etc/ssl/certs/puttputtpal.com.crt
      - ./certs/puttputtpal.com.key:/etc/ssl/private/puttputtpal.com.key
      - ./cloudflare-ips.conf:/etc/nginx/cloudflare-ips.conf
    networks:
      - puttputtpal_net

networks:
  puttputtpal_net:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  redis-data: