version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puttputtpal-server
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env.server.production
    volumes:
      - ./logs/server/:/app/logs/server/
    ports:
      - "7500:7500"
    networks:
      - local_net
    restart: unless-stopped

networks:
  local_net:
    name: local_net
    driver: bridge