version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: puttputtpal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - local_net
      - redis-network

volumes:
  redis-data:

networks:
  local_net:
    name: local_net
    driver: bridge
  redis-network:
    driver: bridge
