name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/puttputtpal-server:latest
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H '${{ secrets.DIGITAL_OCEAN_IP }}' >> ~/.ssh/known_hosts
      - name: Copy docker-compose-server.yml to Droplet
        run: |
          scp ./docker-compose-server.yml root@${{ secrets.DIGITAL_OCEAN_IP }}:/root/devops/docker-compose-server.yml
      - name: Copy docker-compose-proxy.yml to Droplet
        run: |
          scp ./docker-compose-proxy.yml root@${{ secrets.DIGITAL_OCEAN_IP }}:/root/devops/docker-compose-proxy.yml
      - name: Copy nginx.conf to Droplet
        run: |
          scp ./nginx/nginx.conf root@${{ secrets.DIGITAL_OCEAN_IP }}:/root/devops/nginx.conf
      - name: Copy redis.conf to Droplet
        run: |
          scp ./redis/redis.conf root@${{ secrets.DIGITAL_OCEAN_IP }}:/root/devops/redis.conf
      - name: SSH and Docker Compose Up
        run: |
          ssh root@${{ secrets.DIGITAL_OCEAN_IP }} 'cd /root/devops && docker compose pull && docker compose -f docker-compose-server.yml up -d && docker compose -f docker-compose-proxy.yml up -d'